### ISSUE TITLE
Locale should be the first argument

### ISSUE THREAD

**Issue by sffc** [tc39/proposal-intl-messageformat#32]
I saw a slide in the presentation where the message string was first, locale second. We should keep locale as the first argument.

**Comment by eemeli** [comment]
Are you proposing that the arguments should be (locales, source, options) or (locales, options, source)?

My sense is that any which way we go we'll need to break with some precedent, and that (source, locales, options) is the least worst choice as it adds the new required argument first and keeps the optional locales+options arguments together, as they are currently.

The current order was arrived at after some discussion with @gibson042 early on in the proposal.

**Comment by sffc** [comment]
Probably (locales, source, options) since options should be last so that you don't have any trailing arguments after the options bag.

**Comment by FrankYFTang** [comment]
I also agree with sffc. I think locales should be the first arg.
